### ISSUE TITLE
播放器没法用啊，chrome console全是报错，你后台接口有问题吧

### ISSUE THREAD

**Issue by mebest100** [MeetYouZi/pomelomusic#4]
播放器没法用啊，chrome console全是报错，你后台接口有问题吧

![image](https://user-images.githubusercontent.com/11530991/91540174-ff67cb00-e94c-11ea-8bd0-8f275f26ffd0.png)

**Comment by MeetYouZi** [comment]
哦哦。你仔细看下 我的 readme 
你本地开启了后台接口 3000 服务吗？
需要你这边去看下 https://binaryify.github.io/NeteaseCloudMusicApi 接口使用说明哦
